// This Webpack config extends the one generated by electron-webpack
module.exports = {
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        options: {
          presets: ['@babel/react'],
          plugins: [
            '@babel/plugin-proposal-object-rest-spread',
            '@babel/plugin-proposal-class-properties',
            '@babel/plugin-proposal-optional-chaining',
            ['@babel/plugin-transform-runtime', { regenerator: true }]
          ]
        }
      },
      {
        test: /\.jsx?$/,
        use: 'react-hot-loader/webpack',
        include: /node_modules/
      }
    ]
  },
  resolve: {
    extensions: ['.js', '.jsx']
  }
}
